import type { INodeProperties } from 'n8n-workflow';

export const searchTasksFields: INodeProperties[] = [
  {
    displayName: 'Quantity of Items',
    name: 'pageSize',
    type: 'number',
    default: 20,
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Number of items per page',
  },
  {
    displayName: 'Search',
    name: 'query',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Termo de pesquisa',
  },
  {
    displayName: 'Type Name or ID',
    name: 'tipoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getTaskTypes',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Status Name or ID',
    name: 'statusId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getTaskStatuses',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'User Name or ID',
    name: 'usuarioId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Lead ID',
    name: 'leadId',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'ID do lead',
  },
  {
    displayName: 'Project ID',
    name: 'projetoId',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'ID do projeto',
  },
  {
    displayName: 'Store Names or IDs',
    name: 'lojasIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStores',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Start Date',
    name: 'dataInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Data inicial (YYYY-MM-DD)',
  },
  {
    displayName: 'End Date',
    name: 'dataFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Data final (YYYY-MM-DD)',
  },
  {
    displayName: 'Sort By',
    name: 'ordenarPor',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarTarefas'] } },
    description: 'Campo para ordenação',
  },
];
