import { NodePropertyTypes } from 'n8n-workflow';

export const adicionarTarefaFields = [
	{
		displayName: 'Título',
		name: 'titulo',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Descrição',
		name: 'descricao',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Tipo ID',
		name: 'tipoId',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Status ID',
		name: 'statusId',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Projeto ID',
		name: 'projetoId',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Usuários IDs',
		name: 'usuariosIds',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Data Inicial',
		name: 'dataInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
	{
		displayName: 'Data Entrega',
		name: 'dataEntrega',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['adicionarTarefa'] } },
	},
];
