import { NodePropertyTypes } from 'n8n-workflow';

export const enviarMensagemWhatsAppFields = [
	{
		displayName: 'Lead ID',
		name: 'leadId',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Mensagem',
		name: 'mensagem',
		type: 'string' as NodePropertyTypes,
		required: true,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Pré-Vendedor',
		name: 'preVendedor',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Vendedor',
		name: 'vendedor',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Técnico',
		name: 'tecnico',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Lead',
		name: 'lead',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'Celular',
		name: 'celular',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'URL Imagem',
		name: 'urlImagem',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'URL Áudio',
		name: 'urlAudio',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'URL Vídeo',
		name: 'urlVideo',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
	{
		displayName: 'URL Documento',
		name: 'urlDocumento',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
	},
];
