import { NodePropertyTypes } from 'n8n-workflow';

export const pesquisarTarefasFields = [
	{
		displayName: 'Lead ID',
		name: 'leadId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Projeto ID',
		name: 'projetoId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Tipo ID',
		name: 'tipoId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Page Number',
		name: 'pageNumber',
		type: 'number' as NodePropertyTypes,
		default: 1,
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Page Size',
		name: 'pageSize',
		type: 'number' as NodePropertyTypes,
		default: 10,
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Usuário ID',
		name: 'usuarioId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Lojas IDs',
		name: 'lojasIds',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Status ID',
		name: 'statusId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Ordenar Por',
		name: 'ordenarPor',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Data Inicial',
		name: 'dataInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
	{
		displayName: 'Data Final',
		name: 'dataFinal',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarTarefas'] } },
	},
];
