import { NodePropertyTypes } from 'n8n-workflow';

export const pesquisarNegociosFields = [
	{
		displayName: 'Etapa ID',
		name: 'etapaId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Page Number',
		name: 'pageNumber',
		type: 'number' as NodePropertyTypes,
		default: 1,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Page Size',
		name: 'pageSize',
		type: 'number' as NodePropertyTypes,
		default: 10,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Query',
		name: 'query',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Etiquetas IDs',
		name: 'etiquetasIds',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Vendedor Responsável ID',
		name: 'vendedorResponsavelId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Técnico Responsável ID',
		name: 'tecnicoResponsavelId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Tipo Projeto ID',
		name: 'tipoProjetoId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Pré-Vendedor ID',
		name: 'preVendedorId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Lojas IDs',
		name: 'lojasIds',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Origens IDs',
		name: 'origensIds',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Status ID',
		name: 'statusId',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Ordenar Por',
		name: 'ordenarPor',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Consumo Final',
		name: 'consumoFinal',
		type: 'number' as NodePropertyTypes,
		default: 0,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Potência Final',
		name: 'potenciaFinal',
		type: 'number' as NodePropertyTypes,
		default: 0,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Valor Final',
		name: 'valorFinal',
		type: 'number' as NodePropertyTypes,
		default: 0,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Qualificação Inicial',
		name: 'qualificacaoInicial',
		type: 'number' as NodePropertyTypes,
		default: 0,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Qualificação Final',
		name: 'qualificacaoFinal',
		type: 'number' as NodePropertyTypes,
		default: 0,
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Cidade',
		name: 'cidade',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'UF',
		name: 'uf',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Inicial',
		name: 'dataInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Final',
		name: 'dataFinal',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Previsão Fechamento Inicial',
		name: 'dataPrevisaoFechamentoInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Previsão Fechamento Final',
		name: 'dataPrevisaoFechamentoFinal',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Proposta Aceita Inicial',
		name: 'dataPropostaAceitaInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Proposta Aceita Final',
		name: 'dataPropostaAceitaFinal',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Venda Inicial',
		name: 'dataVendaInicial',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
	{
		displayName: 'Data Venda Final',
		name: 'dataVendaFinal',
		type: 'string' as NodePropertyTypes,
		default: '',
		displayOptions: { show: { operation: ['pesquisarNegocios'] } },
	},
];
