import type { INodeProperties } from 'n8n-workflow';

export const sendWhatsAppFields: INodeProperties[] = [
  {
    displayName: 'Contact ID',
    name: 'leadId',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
  },
  {
    displayName: 'Message',
    name: 'mensagem',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Message to be sent',
  },
  {
    displayName: 'Phone',
    name: 'celular',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Phone number',
  },
  {
    displayName: 'Image URL',
    name: 'urlImagem',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
  },
  {
    displayName: 'Audio URL',
    name: 'urlAudio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
  },
  {
    displayName: 'Video URL',
    name: 'urlVideo',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
  },
  {
    displayName: 'Document URL',
    name: 'urlDocumento',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
  },
  {
    displayName: 'Send to Pre-Seller',
    name: 'preVendedor',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Whether to send to Pre-Seller',
  },
  {
    displayName: 'Send to Seller',
    name: 'vendedor',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Whether to send to Seller',
  },
  {
    displayName: 'Send to Technician',
    name: 'tecnico',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Whether to send to Technician',
  },
  {
    displayName: 'Send to Lead',
    name: 'lead',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['enviarMensagemWhatsApp'] } },
    description: 'Whether to send to Lead',
  },
];
