import type { INodeProperties } from 'n8n-workflow';

export const addTaskFields: INodeProperties[] = [
  {
    displayName: 'Title',
    name: 'titulo',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Título da tarefa',
  },
  {
    displayName: 'Description',
    name: 'descricao',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Descrição da tarefa',
  },
  {
    displayName: 'Start Date',
    name: 'dataInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Data inicial (YYYY-MM-DD)',
  },
  {
    displayName: 'Delivery Date',
    name: 'dataEntrega',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Data de entrega (YYYY-MM-DD)',
  },
  {
    displayName: 'Deal ID',
    name: 'projetoId',
    type: 'number',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'ID do Negócio',
  },
  {
    displayName: 'Status Name or ID',
    name: 'statusTarefaId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getTaskStatuses',
    },
    required: true,
    default: '',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Type Name or ID',
    name: 'tipoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getTaskTypes',
    },
    required: true,
    default: '',
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'User Names or IDs',
    name: 'usuariosIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    required: true,
    default: [],
    displayOptions: { show: { operation: ['adicionarTarefa'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
];
