import type { INodeProperties } from 'n8n-workflow';

export const searchDealsFields: INodeProperties[] = [
  {
    displayName: 'Quantity of Items',
    name: 'pageSize',
    type: 'number',
    default: 20,
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Number of items per page',
  },
  {
    displayName: 'Search',
    name: 'query',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'General search term',
  },
  {
    displayName: 'Criteria',
    name: 'criterio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Search criteria',
  },
  {
    displayName: 'Project Type Name or ID',
    name: 'tipoProjetoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getDealTypes',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Stage Name or ID',
    name: 'etapaId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getEtapas',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Status Name or ID',
    name: 'statusId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Responsible Seller Name or ID',
    name: 'vendedorResponsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Responsible Technician Name or ID',
    name: 'tecnicoResponsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Pre Seller Name or ID',
    name: 'preVendedorId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Lead ID',
    name: 'leadId',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
  },
  {
    displayName: 'Store Names or IDs',
    name: 'lojasIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStores',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'City',
    name: 'cidade',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Project city',
  },
  {
    displayName: 'State',
    name: 'uf',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Project state (UF)',
  },
  {
    displayName: 'Initial Power',
    name: 'potenciaInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial power in kW',
  },
  {
    displayName: 'Final Power',
    name: 'potenciaFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final power in kW',
  },
  {
    displayName: 'Initial Value',
    name: 'valorInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial project value',
  },
  {
    displayName: 'Final Value',
    name: 'valorFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final project value',
  },
  {
    displayName: 'Initial Consumption',
    name: 'consumoInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial consumption in kWh',
  },
  {
    displayName: 'Final Consumption',
    name: 'consumoFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final consumption in kWh',
  },
  {
    displayName: 'Tag Names or IDs',
    name: 'etiquetasIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getTags',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Origin Names or IDs',
    name: 'origensIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getOrigins',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Status History IDs',
    name: 'statusHistoricoIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'N Status History IDs',
    name: 'nStatusHistoricoIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Start Date',
    name: 'dataInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Start date (YYYY-MM-DD)',
  },
  {
    displayName: 'End Date',
    name: 'dataFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'End date (YYYY-MM-DD)',
  },
  {
    displayName: 'Initial Closing Forecast Date',
    name: 'dataPrevisaoFechamentoInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial closing forecast date (YYYY-MM-DD)',
  },
  {
    displayName: 'Final Closing Forecast Date',
    name: 'dataPrevisaoFechamentoFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final closing forecast date (YYYY-MM-DD)',
  },
  {
    displayName: 'Initial Accepted Proposal Date',
    name: 'dataPropostaAceitaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial accepted proposal date (YYYY-MM-DD)',
  },
  {
    displayName: 'Final Accepted Proposal Date',
    name: 'dataPropostaAceitaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final accepted proposal date (YYYY-MM-DD)',
  },
  {
    displayName: 'Initial Sale Date',
    name: 'dataVendaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial sale date (YYYY-MM-DD)',
  },
  {
    displayName: 'Final Sale Date',
    name: 'dataVendaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final sale date (YYYY-MM-DD)',
  },
  {
    displayName: 'Initial Loss Date',
    name: 'dataPerdaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial loss date (YYYY-MM-DD)',
  },
  {
    displayName: 'Final Loss Date',
    name: 'dataPerdaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final loss date (YYYY-MM-DD)',
  },
  {
    displayName: 'Sort By',
    name: 'ordenarPor',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Field for sorting',
  },
  {
    displayName: 'Initial Qualification',
    name: 'qualificacaoInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Initial qualification (0-10)',
  },
  {
    displayName: 'Final Qualification',
    name: 'qualificacaoFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Final qualification (0-10)',
  },
  {
    displayName: 'Indicator',
    name: 'indicador',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Performance indicator',
  },
  {
    displayName: 'Contact Owner ID',
    name: 'donoContatoId',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
  },
  {
    displayName: 'Campaign',
    name: 'campanha',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Marketing campaign',
  },
  {
    displayName: 'Advertisement',
    name: 'anuncio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Marketing advertisement',
  },
  {
    displayName: 'Ad Set',
    name: 'conjuntoAnuncios',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
  },
];
