import type { INodeProperties } from 'n8n-workflow';

export const searchDealsFields: INodeProperties[] = [
  {
    displayName: 'Quantity of Items',
    name: 'pageSize',
    type: 'number',
    default: 20,
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Number of items per page',
  },
  {
    displayName: 'Pesquisar',
    name: 'query',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Termo de pesquisa geral',
  },
  {
    displayName: 'Criterio',
    name: 'criterio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Critério de pesquisa',
  },
  {
    displayName: 'Tipo Projeto Name or ID',
    name: 'tipoProjetoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getDealTypes',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Etapa Name or ID',
    name: 'etapaId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getEtapas',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Status Name or ID',
    name: 'statusId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Responsible Seller Name or ID',
    name: 'vendedorResponsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Responsible Technician Name or ID',
    name: 'tecnicoResponsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Pre Vendedor Name or ID',
    name: 'preVendedorId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Lead ID',
    name: 'leadId',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'ID do lead',
  },
  {
    displayName: 'Store Names or IDs',
    name: 'lojasIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStores',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Cidade',
    name: 'cidade',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Cidade do projeto',
  },
  {
    displayName: 'UF',
    name: 'uf',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Estado (UF) do projeto',
  },
  {
    displayName: 'Potencia Inicial',
    name: 'potenciaInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Potência inicial em kW',
  },
  {
    displayName: 'Potencia Final',
    name: 'potenciaFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Potência final em kW',
  },
  {
    displayName: 'Valor Inicial',
    name: 'valorInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Valor inicial do projeto',
  },
  {
    displayName: 'Valor Final',
    name: 'valorFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Valor final do projeto',
  },
  {
    displayName: 'Consumo Inicial',
    name: 'consumoInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Consumo inicial em kWh',
  },
  {
    displayName: 'Consumo Final',
    name: 'consumoFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Consumo final em kWh',
  },
  {
    displayName: 'Tag Names or IDs',
    name: 'etiquetasIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getTags',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Origin Names or IDs',
    name: 'origensIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getOrigins',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Status Historico IDs',
    name: 'statusHistoricoIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'N Status Historico IDs',
    name: 'nStatusHistoricoIds',
    type: 'multiOptions',
    typeOptions: {
      loadOptionsMethod: 'getStatuses',
    },
    default: [],
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Choose from the list, or specify IDs using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Data Inicial',
    name: 'dataInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data inicial (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Final',
    name: 'dataFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data final (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Previsao Fechamento Inicial',
    name: 'dataPrevisaoFechamentoInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data inicial de previsão de fechamento (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Previsao Fechamento Final',
    name: 'dataPrevisaoFechamentoFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data final de previsão de fechamento (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Proposta Aceita Inicial',
    name: 'dataPropostaAceitaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data inicial de proposta aceita (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Proposta Aceita Final',
    name: 'dataPropostaAceitaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data final de proposta aceita (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Venda Inicial',
    name: 'dataVendaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data inicial de venda (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Venda Final',
    name: 'dataVendaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data final de venda (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Perda Inicial',
    name: 'dataPerdaInicial',
    type: 'string',
    default: '',
    placeholder: '2024-01-01',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data inicial de perda (YYYY-MM-DD)',
  },
  {
    displayName: 'Data Perda Final',
    name: 'dataPerdaFinal',
    type: 'string',
    default: '',
    placeholder: '2024-12-31',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Data final de perda (YYYY-MM-DD)',
  },
  {
    displayName: 'Ordenar Por',
    name: 'ordenarPor',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Campo para ordenação',
  },
  {
    displayName: 'Qualificacao Inicial',
    name: 'qualificacaoInicial',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Qualificação inicial (0-10)',
  },
  {
    displayName: 'Qualificacao Final',
    name: 'qualificacaoFinal',
    type: 'number',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Qualificação final (0-10)',
  },
  {
    displayName: 'Indicador',
    name: 'indicador',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Indicador de performance',
  },
  {
    displayName: 'Dono Contato ID',
    name: 'donoContatoId',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'ID do dono do contato',
  },
  {
    displayName: 'Campanha',
    name: 'campanha',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Campanha de marketing',
  },
  {
    displayName: 'Anuncio',
    name: 'anuncio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Anúncio de marketing',
  },
  {
    displayName: 'Conjunto Anuncios',
    name: 'conjuntoAnuncios',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['pesquisarNegocios'] } },
    description: 'Conjunto de anúncios',
  },
];
