import type { INodeProperties } from 'n8n-workflow';

export const createDealFields: INodeProperties[] = [
  {
    displayName: 'Name',
    name: 'nome',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Lead/deal name',
  },
  {
    displayName: 'Email',
    name: 'email',
    type: 'string',
    required: true,
    default: '',
    placeholder: 'name@email.com',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Lead email',
  },
  {
    displayName: 'Phone',
    name: 'telefone',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Lead phone number',
  },
  {
    displayName: 'City',
    name: 'cidade',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Lead city',
  },
  {
    displayName: 'Document',
    name: 'documento',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'CPF/CNPJ number',
  },
  {
    displayName: 'Person Type',
    name: 'tipoPessoa',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Person type (Individual/Company)',
  },
  {
    displayName: 'State',
    name: 'uf',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'State (UF)',
  },
  {
    displayName: 'Account Value',
    name: 'valorConta',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
  },
  {
    displayName: 'Responsible Name or ID',
    name: 'responsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Responsible Email',
    name: 'emailResponsavel',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Responsible person email',
  },
  {
    displayName: 'Note',
    name: 'nota',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Observation/note',
  },
  {
    displayName: 'Campaign',
    name: 'campanha',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Origin campaign',
  },
  {
    displayName: 'Ad',
    name: 'anuncio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Origin advertisement',
  },
  {
    displayName: 'Ad Set',
    name: 'conjuntoAnuncios',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
  },
  {
    displayName: 'Lead Tracking Code',
    name: 'codigoLeadTracking',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
  },
  {
    displayName: 'Trade Name',
    name: 'nomeFantasia',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
  },
  {
    displayName: 'Segment',
    name: 'segmento',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Business segment',
  },
  {
    displayName: 'Deal Type Name or ID',
    name: 'tipoProjetoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getDealTypes',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Origin Name or ID',
    name: 'codOrigem',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getOrigins',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>. Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>.',
  },
  {
    displayName: 'Custom URL',
    name: 'url',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Custom URL (optional)',
  },
];
