import type { INodeProperties } from 'n8n-workflow';

export const createDealFields: INodeProperties[] = [
  {
    displayName: 'Name',
    name: 'nome',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Nome do lead/negócio',
  },
  {
    displayName: 'Email',
    name: 'email',
    type: 'string',
    required: true,
    default: '',
    placeholder: 'name@email.com',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Email do lead',
  },
  {
    displayName: 'Phone',
    name: 'telefone',
    type: 'string',
    required: true,
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Telefone do lead',
  },
  {
    displayName: 'City',
    name: 'cidade',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Cidade do lead',
  },
  {
    displayName: 'Document',
    name: 'documento',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'CPF/CNPJ do lead',
  },
  {
    displayName: 'Person Type',
    name: 'tipoPessoa',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Tipo de pessoa (Física/Jurídica)',
  },
  {
    displayName: 'State',
    name: 'uf',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Estado (UF) do lead',
  },
  {
    displayName: 'Account Value',
    name: 'valorConta',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Valor da conta',
  },
  {
    displayName: 'Responsible Name or ID',
    name: 'responsavelId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getResponsibles',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Responsible Email',
    name: 'emailResponsavel',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Email do responsável',
  },
  {
    displayName: 'Note',
    name: 'nota',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Observação/nota',
  },
  {
    displayName: 'Campaign',
    name: 'campanha',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Campanha de origem',
  },
  {
    displayName: 'Ad',
    name: 'anuncio',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Anúncio de origem',
  },
  {
    displayName: 'Ad Set',
    name: 'conjuntoAnuncios',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Conjunto de anúncios',
  },
  {
    displayName: 'Lead Tracking Code',
    name: 'codigoLeadTracking',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Código de tracking do lead',
  },
  {
    displayName: 'Trade Name',
    name: 'nomeFantasia',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Nome fantasia',
  },
  {
    displayName: 'Segment',
    name: 'segmento',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Segmento do negócio',
  },
  {
    displayName: 'Deal Type Name or ID',
    name: 'tipoProjetoId',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getDealTypes',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Origin Name or ID',
    name: 'codOrigem',
    type: 'options',
    typeOptions: {
      loadOptionsMethod: 'getOrigins',
    },
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code-examples/expressions/">expression</a>',
  },
  {
    displayName: 'Custom URL',
    name: 'url',
    type: 'string',
    default: '',
    displayOptions: { show: { operation: ['criarNegocio'] } },
    description: 'URL customizada (opcional)',
  },
];
